parameters:
  - name: isDeployRun # Indicates if this build is part of a deployment pipeline run
    type: boolean
    default: false
  - name: stageName
    type: string
  - name: displayName
    type: string
  - name: dotnetEfVersion # Version of dotnet-ef tool to use
    type: string
    default: '8.0.4'
  
stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.displayName }}
    jobs:
    - job:
      pool:
        name: Azure Pipelines
        vmImage: 'ubuntu-latest'
      steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.0.x'

      - task: DotNetCoreCLI@2
        displayName: 'Restore'
        inputs:
          command: 'restore'
          projects: '$(solution)'
          verbosityRestore: 'Minimal'

      - task: CmdLine@2
        displayName: 'Build migrations bundle'
        condition: eq(${{ parameters.isDeployRun }}, true) # Task only runs for deployment pipeline runs
        inputs:
          script: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install --global dotnet-ef --version ${{ parameters.dotnetEfVersion }}
            dotnet ef migrations bundle --verbose --self-contained -r linux-x64 --project CheckYourEligibility.API/CheckYourEligibility.API.csproj
            mv efbundle $(Build.ArtifactStagingDirectory)
          failOnStderr: true

      - task: DotNetCoreCLI@2
        displayName: 'Build solution'
        inputs:
          command: 'build'
          projects: '$(solution)'
          arguments: '--configuration $(buildConfiguration) --verbosity minimal'

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: 'test'
          projects: 'CheckYourEligibility.API.Tests/CheckYourEligibility.API.Tests.csproj'
          arguments: '--configuration $(buildConfiguration) --verbosity minimal'
          publishTestResults: true
          testRunTitle: 'Unit Tests'

      - task: DotNetCoreCLI@2
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: True

      - task: CopyFiles@2
        inputs:
          SourceFolder: 'tests'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/tests'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)' 
          artifactName: 'checkYourEligibilityAPI'
