parameters:
  - name: isDeployRun # Indicates if this build is part of a deployment pipeline run
    type: boolean
    default: false
  - name: stageName
    type: string
  - name: displayName
    type: string
  
stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.displayName }}
    jobs:
    - job:
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.0.x'

      - task: DotNetCoreCLI@2
        displayName: 'Restore'
        inputs:
          command: 'restore'
          projects: '$(solution)'

      - task: CmdLine@2
        displayName: 'Build migrations bundle'
        condition: eq(${{ parameters.isDeployRun }}, true) # Task only runs for deployment pipeline runs
        inputs:
          script: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install --global dotnet-ef --version 8.0.4
            dotnet ef migrations bundle --verbose --self-contained -r linux-x64 --project CheckYourEligibility.API/CheckYourEligibility.API.csproj
            mv efbundle $(Build.ArtifactStagingDirectory)

      - task: DotNetCoreCLI@2
        displayName: 'Build solution'
        inputs:
          command: 'build'
          projects: '$(solution)'
          arguments: '--configuration $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'Run tests'
        inputs:
          command: 'test'
          projects: 'CheckYourEligibility.API.Tests/CheckYourEligibility.API.Tests.csproj'
          arguments: '--configuration $(buildConfiguration) --logger "trx;LogFileName=TestResults.trx" --results-directory $(Build.ArtifactStagingDirectory)/Test/Results'

      - task: DotNetCoreCLI@2
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: True

      - task: CopyFiles@2
        inputs:
          SourceFolder: 'tests'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/tests'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)' 
          artifactName: 'checkYourEligibilityAPI'
