parameters:
  - name: stageName
    type: string
  - name: displayName
    type: string
  - name: deploymentName
    type: string
  - name: environment
    type: string
  - name: ECE_KEY_VAULT_NAME
    type: string
  - name: azureSubscription
    type: string
  - name: azureResourceGroup
    type: string
  - name: sqlServerName
    type: string
  - name: webAppName
    type: string
  - name: prefix
    type: string

  
stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.displayName }}
  jobs:
  - deployment: ${{ parameters.deploymentName }}
    displayName: ${{ parameters.displayName }}
    pool:
      name: ${{ parameters.prefix }}-ECE-managed-devops-pool
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        preDeploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              targetPath: '$(Pipeline.Workspace)'
          - task: AzureCLI@2
            displayName: 'Run Migrations'
            env:
              ECE_KEY_VAULT_NAME: ${{ parameters.ECE_KEY_VAULT_NAME }}
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                cd $(Pipeline.Workspace)/checkYourEligibilityAPI && \
                chmod +x ./efbundle && \
                ./efbundle
        
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: ${{ parameters.azureSubscription }}
              appType: 'webApp'
              WebAppName: ${{ parameters.webAppName }}
              packageForLinux: '$(Pipeline.Workspace)/checkYourEligibilityAPI/CheckYourEligibility.API.zip'