using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace CheckYourEligibility.API.Domain;

[ExcludeFromCodeCoverage(Justification = "Data Model.")]
public class MultiAcademyTrustSchool
{
    [Key] public int ID { get; set; } //TODO: AutoGenerated
    public int TrustId { get; set; }
    public int SchoolId { get; set; }
    public virtual MultiAcademyTrust MultiAcademyTrust { get; set; }
}