trigger:
  - capi

pr: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: BuildApp
    displayName: Build App
    jobs:
      #- template: templates/app-build.yml@templates
    - job: 
      pool:
        name: Azure Pipelines
        vmImage: 'windows-latest'
      steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'
          
      - task: CmdLine@2
        displayName: 'Build migrations bundle'
        inputs:
          script: |
            dotnet tool install --global dotnet-ef --version 8.0.4
            dotnet ef migrations bundle --verbose --self-contained -r win-x86 --project CheckYourEligibility.API/CheckYourEligibility.API.csproj
            mv efbundle.exe $(Build.ArtifactStagingDirectory)

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: VSTest@2
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          runSettingsFile: 'CheckYourEligibility.API.Tests/.runsettings'
          resultsFolder: '$(build.ArtifactStagingDirectory)/Test/Results'
          otherConsoleOptions: '/collect:"Code Coverage;Format=Cobertura"'  # <<<< this is the important bit
          codeCoverageEnabled: True

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: '$(build.ArtifactStagingDirectory)/Test/Results/**/*.xml'

      - task: DotNetCoreCLI@2
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: True
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)' 
          artifactName: 'checkYourEligibilityAPI'

  - stage: DeployApp
    displayName: Deploy App Production
    jobs:
    - deployment: deploy
      displayName: Deploy App Production
      pool:
        name: Azure Pipelines
        vmImage: 'windows-latest'
      environment: PROD
      strategy:
        runOnce:
          preDeploy:
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                targetPath: '$(Pipeline.Workspace)'
            - task: AzureCLI@2
              displayName: 'Run Migrations'
              env:
                ECE_KEY_VAULT_NAME: ece-kv-ece
              inputs:
                azureSubscription: 's203p.azdo.deployment'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az sql server firewall-rule create -g s203p01-core1 --server ece-database --name ADO-Deploy --start-ip-address $(curl ipinfo.io/ip) --end-ip-address $(curl ipinfo.io/ip) &&\
                  cd D:/a/1/checkYourEligibilityAPI &&\
                  ./efbundle.exe &&\
                  az sql server firewall-rule delete -g s203p01-core1 --server ece-database --name ADO-Deploy
          
          deploy:
            steps:
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 's203p.azdo.deployment'
                appType: 'webApp'
                WebAppName: 'ece-as-capi'
                packageForLinux: '$(Pipeline.Workspace)/checkYourEligibilityAPI/CheckYourEligibility.API.zip'