//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckYourEligibility.Core.Tests.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckYourEligibility.Core.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///    &lt;s:Header&gt;
        ///        &lt;ActivityId CorrelationId=&quot;f1f78b7e-a8f3-4772-bcb0-6273e8139d58&quot; xmlns=&quot;http://schemas.microsoft.com/2004/09/ServiceModel/Diagnostics&quot;&gt;00000000-0000-0000-0000-000000000000&lt;/ActivityId&gt;
        ///    &lt;/s:Header&gt;
        ///    &lt;s:Body&gt;
        ///        &lt;SubmitSingleQueryResponse xmlns=&quot;http://www.dcsf.gov.uk/20090308/&quot;&gt;
        ///            &lt;SubmitSingleQueryResult xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///                &lt;EligibilityStatus&gt;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EcsSoapEligible
        {
            get
            {
                return ResourceManager.GetString("EcsSoapEligible", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;FreeSchoolMealsHMRC xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///                     xsi:schemaLocation=&quot;http://www.govtalk.gov.uk/Education/FreeSchoolMeals-200705&quot;
        ///                     xmlns=&quot;http://www.govtalk.gov.uk/Education/FreeSchoolMeals-200705&quot;&gt;
        ///    &lt;Header&gt;
        ///        &lt;OriginatingSystemID&gt;FS&lt;/OriginatingSystemID&gt;
        ///        &lt;ReceivingSystemID&gt;DE&lt;/ReceivingSystemID&gt;
        ///        &lt;CreationDate&gt;20240221&lt;/CreationDate&gt; &lt;!-- yyyymmdd --&gt;
        ///        &lt;Creation [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exampleHMRC
        {
            get
            {
                return ResourceManager.GetString("exampleHMRC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;FreeSchoolMealsHMRC xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///                     xsi:schemaLocation=&quot;http://www.govtalk.gov.uk/Education/FreeSchoolMeals-200705&quot;
        ///                     xmlns=&quot;http://www.govtalk.gov.uk/Education/FreeSchoolMeals-200705&quot;&gt;
        ///    &lt;Header&gt;
        ///        &lt;OriginatingSystemID&gt;FS&lt;/OriginatingSystemID&gt;
        ///        &lt;ReceivingSystemID&gt;DE&lt;/ReceivingSystemID&gt;
        ///        &lt;CreationDate&gt;20240221&lt;/CreationDate&gt; &lt;!-- yyyymmdd --&gt;
        ///        &lt;Creation [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exampleHMRC_empty
        {
            get
            {
                return ResourceManager.GetString("exampleHMRC_empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 19000001,19760509,Charlton
        ///19000002,19760509,Cohen
        ///19000003,19760509,Moore
        ///19000004,19760509,Wilson
        ///19000005,19760509,Ball
        ///19000006,19760509,Stiles
        ///19000007,19760509,Charlton
        ///19000008,19760509,Peters
        ///19000009,19760509,Hunt
        ///19000010,19760509,Hurst
        ///19000011,19760509,Banks
        ///19000012,19760509,Hottges
        ///19000013,19760509,Schulz
        ///19000014,19760509,Weber
        ///19000015,19760509,Schnellinger
        ///19000016,19760509,Beckenbauer
        ///19000017,19760509,Haller
        ///19000018,19760509,Overath
        ///19000019,19760509,Emmerich
        ///19000020 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HO_Data_small
        {
            get
            {
                return ResourceManager.GetString("HO Data small", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to URN,LA (code),LA (name),EstablishmentNumber,EstablishmentName,TypeOfEstablishment (code),TypeOfEstablishment (name),EstablishmentTypeGroup (code),EstablishmentTypeGroup (name),EstablishmentStatus (code),EstablishmentStatus (name),ReasonEstablishmentOpened (code),ReasonEstablishmentOpened (name),OpenDate,ReasonEstablishmentClosed (code),ReasonEstablishmentClosed (name),CloseDate,PhaseOfEducation (code),PhaseOfEducation (name),StatutoryLowAge,StatutoryHighAge,Boarders (code),Boarders (name),NurseryProvision ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string small_gis
        {
            get
            {
                return ResourceManager.GetString("small_gis", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group UID,Group ID,Group Name,Companies House Number,Group Type (code),Group Type,Closed Date,Open date,Incorporated on (open date),Group Status (code),Group Status,Joined date,Academy URN,Trust Academy Establishment Name,TypeOfEstablishment (code),TypeOfEstablishment (name),PhaseOfEducation (code),PhaseOfEducation (name),LA (code),LA (name)
        ///17101,TR01904,5 DIMENSIONS TRUST,07595434,06,Multi-academy trust,,,07/04/2011,OPEN,Open,01/05/2011,136730,Shenley Brook End School,34,Academy converter,4,Secondary,826 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string small_mat
        {
            get
            {
                return ResourceManager.GetString("small_mat", resourceCulture);
            }
        }
    }
}
