// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckYourEligibility.API.Migrations
{
    [DbContext(typeof(EligibilityCheckContext))]
    partial class EligibilityCheckContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheckYourEligibility.API.Domain.Application", b =>
                {
                    b.Property<string>("ApplicationID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ChildDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChildFirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ChildLastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("EligibilityCheckHashID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EligibilityEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<int>("LocalAuthorityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ParentDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentEmail")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ParentFirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ParentLastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ParentNationalAsylumSeekerServiceNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ParentNationalInsuranceNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ApplicationID");

                    b.HasIndex("EligibilityCheckHashID");

                    b.HasIndex("EstablishmentId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Status" }, "idx_ApplicationStatus");

                    b.HasIndex(new[] { "Reference" }, "idx_Reference")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.ApplicationEvidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StorageAccountReference")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ApplicationID" }, "idx_ApplicationEvidence_ApplicationID");

                    b.ToTable("ApplicationEvidence");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.ApplicationStatus", b =>
                {
                    b.Property<string>("ApplicationStatusID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ApplicationStatusID");

                    b.HasIndex("ApplicationID");

                    b.ToTable("ApplicationStatuses");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.Audit", b =>
                {
                    b.Property<string>("AuditID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("authentication")
                        .IsRequired()
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("scope")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("typeId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("AuditID");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.BulkCheck", b =>
                {
                    b.Property<string>("BulkCheckID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EligibilityType")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("LocalAuthorityId")
                        .HasColumnType("int");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BulkCheckID");

                    b.HasIndex("LocalAuthorityId");

                    b.ToTable("BulkChecks");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.ECSConflict", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CAPIEndpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CAPIResponseCode")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ECE_Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ECS_Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EligibilityCheckHashID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nino")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("EligibilityCheckHashID");

                    b.ToTable("ECSConflicts");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.EligibilityCheck", b =>
                {
                    b.Property<string>("EligibilityCheckID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BulkCheckID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CheckData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("EligibilityCheckHashID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("EligibilityCheckID");

                    b.HasIndex("BulkCheckID");

                    b.HasIndex("EligibilityCheckHashID");

                    b.ToTable("EligibilityCheck", (string)null);
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.EligibilityCheckHash", b =>
                {
                    b.Property<string>("EligibilityCheckHashID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("EligibilityCheckHashID");

                    b.HasIndex(new[] { "Hash" }, "idx_EligibilityCheckHash");

                    b.ToTable("EligibilityCheckHashes");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.Establishment", b =>
                {
                    b.Property<int>("EstablishmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstablishmentId"));

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstablishmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalAuthorityId")
                        .HasColumnType("int");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusOpen")
                        .HasColumnType("bit");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("EstablishmentId");

                    b.HasIndex("LocalAuthorityId");

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.FreeSchoolMealsHMRC", b =>
                {
                    b.Property<string>("FreeSchoolMealsHMRCID")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("FreeSchoolMealsHMRCID");

                    b.ToTable("FreeSchoolMealsHMRC");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.FreeSchoolMealsHO", b =>
                {
                    b.Property<string>("FreeSchoolMealsHOID")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NASS")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("FreeSchoolMealsHOID");

                    b.ToTable("FreeSchoolMealsHO");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.LocalAuthority", b =>
                {
                    b.Property<int>("LocalAuthorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalAuthorityId"));

                    b.Property<string>("LaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocalAuthorityId");

                    b.ToTable("LocalAuthorities");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.MultiAcademyTrust", b =>
                {
                    b.Property<int>("UID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.ToTable("MultiAcademyTrusts");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.MultiAcademyTrustSchool", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int>("TrustId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TrustId");

                    b.ToTable("MultiAcademyTrustSchools");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.RateLimitEvent", b =>
                {
                    b.Property<string>("RateLimitEventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<string>("PartitionName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("QuerySize")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("RateLimitEventId");

                    b.ToTable("RateLimitEvents");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.HasKey("UserID");

                    b.HasIndex("Email", "Reference")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.WorkingFamiliesEvent", b =>
                {
                    b.Property<string>("WorkingFamiliesEventId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ChildDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChildFirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChildLastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DiscretionaryValidityStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EligibilityCode")
                        .IsRequired()
                        .HasColumnType("nchar(11)");

                    b.Property<DateTime>("GracePeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentFirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ParentLastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ParentNationalInsuranceNumber")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PartnerFirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PartnerLastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PartnerNationalInsuranceNumber")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidityEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidityStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkingFamiliesEventId");

                    b.ToTable("WorkingFamiliesEvents");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.Application", b =>
                {
                    b.HasOne("CheckYourEligibility.API.Domain.EligibilityCheckHash", "EligibilityCheckHash")
                        .WithMany()
                        .HasForeignKey("EligibilityCheckHashID");

                    b.HasOne("CheckYourEligibility.API.Domain.Establishment", "Establishment")
                        .WithMany()
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheckYourEligibility.API.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("EligibilityCheckHash");

                    b.Navigation("Establishment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.ApplicationEvidence", b =>
                {
                    b.HasOne("CheckYourEligibility.API.Domain.Application", "Application")
                        .WithMany("Evidence")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.ApplicationStatus", b =>
                {
                    b.HasOne("CheckYourEligibility.API.Domain.Application", "Application")
                        .WithMany("Statuses")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.BulkCheck", b =>
                {
                    b.HasOne("CheckYourEligibility.API.Domain.LocalAuthority", "LocalAuthority")
                        .WithMany()
                        .HasForeignKey("LocalAuthorityId");

                    b.Navigation("LocalAuthority");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.ECSConflict", b =>
                {
                    b.HasOne("CheckYourEligibility.API.Domain.EligibilityCheckHash", "EligibilityCheckHash")
                        .WithMany()
                        .HasForeignKey("EligibilityCheckHashID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EligibilityCheckHash");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.EligibilityCheck", b =>
                {
                    b.HasOne("CheckYourEligibility.API.Domain.BulkCheck", "BulkCheck")
                        .WithMany("EligibilityChecks")
                        .HasForeignKey("BulkCheckID");

                    b.HasOne("CheckYourEligibility.API.Domain.EligibilityCheckHash", "EligibilityCheckHash")
                        .WithMany()
                        .HasForeignKey("EligibilityCheckHashID");

                    b.Navigation("BulkCheck");

                    b.Navigation("EligibilityCheckHash");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.Establishment", b =>
                {
                    b.HasOne("CheckYourEligibility.API.Domain.LocalAuthority", "LocalAuthority")
                        .WithMany()
                        .HasForeignKey("LocalAuthorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalAuthority");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.MultiAcademyTrustSchool", b =>
                {
                    b.HasOne("CheckYourEligibility.API.Domain.MultiAcademyTrust", "MultiAcademyTrust")
                        .WithMany("MultiAcademyTrustSchools")
                        .HasForeignKey("TrustId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MultiAcademyTrust");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.Application", b =>
                {
                    b.Navigation("Evidence");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.BulkCheck", b =>
                {
                    b.Navigation("EligibilityChecks");
                });

            modelBuilder.Entity("CheckYourEligibility.API.Domain.MultiAcademyTrust", b =>
                {
                    b.Navigation("MultiAcademyTrustSchools");
                });
#pragma warning restore 612, 618
        }
    }
}
